### ISSUE TITLE
ButtonComponent

### ISSUE THREAD

**Issue by Tarek994** [Tarek994/wizardamigos_tar#3]
## `@todo`

#3

- [x] Create a Button component to place  in tab
   - [ ] Add a leading icon
   - [ ] Add the button text
   - [ ] Make the button auto layout
   - [ ] Add border-radius at 6px
   - `@output` :question:  [`ButtonComponent`]( example.com ) from [`comment`]( example.com )

**Comment by Tarek994** [comment]
Create a new task

**Comment by Tarek994** [comment]
## `@todo`

#3

- [ ] Create a Button component to place  in tab
   - [ ] Add a leading icon
   - [ ] Add the button text
   - [ ] Make the button auto layout
   - [ ] Add border-radius at 6px
   - `@output`  ?  `ButtonComponent`
          - next #3
