### ISSUE TITLE
WizardAmigos Events Page

### ISSUE THREAD

**Issue by Tarek994** [Tarek994/wizardamigos_tar#6]
### `@todo`

* [ ] Make WizardAmigos Event Page
    * [ ] Scrape and download all data from meetup.com/wizardamigos
    * [ ] Upload all that data (text/images) to files and folders in the `wizardamigos_tar` repository
    * [ ] Design a GitHub page that uses the data and looks approximately like meetup.com/wizardamigos
    * [ ] Add a timeline component to show the event history in the calendar 
- `@output` :question:  [`WizardAmigos Events`]( example.com ) from [`comment`]( example.com )
